classDiagram
    class User {
        +Id: UUID4
        +FirstName: String
        +LastName: String
        +Email: String
        +Password: String
        +isAdmin: Boolean
        +Register()
        +Update()
        +Delete()
    }